logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  profiles:
    #运行的环境
    active: local
  application:
    name: yl-tool-box
  datasource:
    url: jdbc:mysql://${yl.mysql.ip}:${yl.mysql.port}/${yl.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${yl.mysql.username}
    password: ${yl.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  redis:
#    # Redis服务器地址
#    host: ${yl.redis.host}
#    # Redis服务器端口号
#    port: ${yl.redis.port}
#    # 使用的数据库索引，默认是0
#    database: 0
#    # 连接超时时间
#    timeout: 1800000
#    # 设置密码
#    password: ${yl.redis.password}
#  jackson:
#    serialization:
#      write-dates-as-timestamps: true
