services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/root/docker/software/mysql-8
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network: