server:
  port: 8086
  servlet:
    #============ 中文编码乱码问题，spring-boot 2.X ==========#
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  redis:
    password: ${yl.redis.password}
    host: ${yl.redis.host}
    port: ${yl.redis.port}
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 0
        min-idle: 5
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
    # 连接超时时间（毫秒）
    timeout: 10000ms
## lettuce 日志等级
logging:
  level:
    io.lettuce.core.protocol.RedisStateMachine: info
    io.lettuce.core.protocol.CommandHandler: info
    io.lettuce.core.protocol.CommandEncoder: info
    io.lettuce.core.protocol.DefaultEndpoint: info
    io.lettuce.core.RedisChannelHandler: info

