server:
  port: 8086
  servlet:
    #============ 中文编码乱码问题，spring-boot 2.X ==========#
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  redis:
    password: ${yl.redis.password}
    host: ${yl.redis.host}
    port: ${yl.redis.port}
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认 8
        max-idle: 10
        # 连接池中的最小空闲连接 默认 0
        min-idle: 5
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
    # 连接超时时间（毫秒）
    timeout: 10000ms
## lettuce 日志等级
logging:
  level:
    io.lettuce.core.protocol.RedisStateMachine: info
    io.lettuce.core.protocol.CommandHandler: info
    io.lettuce.core.protocol.CommandEncoder: info
    io.lettuce.core.protocol.DefaultEndpoint: info
    io.lettuce.core.RedisChannelHandler: info
  #============ 禁用Jackson的科学计数法的序列化与反序列化=========#
  jackson:
    deserialization:
      USE_BIG_DECIMAL_FOR_FLOATS : true
    serialization:
      WRITE_BIGDECIMAL_AS_PLAIN : true
  #============ 数据源配置 ==========#
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10
      max-active: 50
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      min-idle: 10
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
    password: ${yl.mysql.password}
    url: jdbc:mysql://${yl.mysql.host}:${yl.mysql.port}/${yl.mysql.db}?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false&useAffectedRows=true
    username: ${yl.mysql.username}


canal:
  server:
    host: 121.199.60.142
    port: 11111
  destination: example
  username: root
  password: root
