
spring:
  redis:
    host: ${yl.redis.host}
    port: 6379
    password: ${yl.redis.password}
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5
    # 连接超时时间（毫秒）
    timeout: 10000ms
  profiles:
    active: local

## lettuce 日志等级
#logging:
#  level:
#    io.lettuce.core.protocol.RedisStateMachine: info
#    io.lettuce.core.protocol.CommandHandler: info
#    io.lettuce.core.protocol.CommandEncoder: info
#    io.lettuce.core.protocol.DefaultEndpoint: info
#    io.lettuce.core.RedisChannelHandler: info
